### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'address')`

### ISSUE THREAD

**Issue by zhutoulala** [Elements-Studio/interface#8]
## URL
  
https://starswap.xyz/#/farm/STAR/STC

## Error

```
TypeError: Cannot read properties of undefined (reading 'address')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'address')
    at LI (https://starswap.xyz/static/js/main.030c9254.chunk.js:1:526723)
    at no (https://starswap.xyz/static/js/4.0970cd9f.chunk.js:1:2238333)
    at Js (https://starswap.xyz/static/js/4.0970cd9f.chunk.js:1:2290791)
    at Au (https://starswap.xyz/static/js/4.0970cd9f.chunk.js:1:2277965)
    at Su (https://starswap.xyz/static/js/4.0970cd9f.chunk.js:1:2277893)
    at Eu (https://starswap.xyz/static/js/4.0970cd9f.chunk.js:1:2277756)
    at mu (https://starswap.xyz/static/js/4.0970cd9f.chunk.js:1:2274722)
    at https://starswap.xyz/static/js/4.0970cd9f.chunk.js:1:2224101
    at t.unstable_runWithPriority (https://starswap.xyz/static/js/4.0970cd9f.chunk.js:1:2301520)
    at Hi (https://starswap.xyz/static/js/4.0970cd9f.chunk.js:1:2223878)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "98.0.4758.102",
    "major": "98"
  },
  "engine": {
    "name": "Blink",
    "version": "98.0.4758.102"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by GravitateX** [comment]
Fixed. Thanks for the issue. Have a good day.
